# Performance parts database
from typing import List, Dict

PARTS_DB: List[Dict] = [
    {'id': 'cold-air-intake', 'name': 'Cold Air Intake System', 'category': 'intake', 'powerGain': 12, 'torqueGain': 18, 'boostGain': 0, 'timingGain': 0, 'cost': 499, 'difficulty': 1, 'stages': [1], 'description': 'High-flow conical air filter with thermal shield.', 'compatible': ['all'], 'requiredECU': False, 'warrantyRisk': 'Low'},
    {'id': 'exhaust-system', 'name': 'Cat-Back Exhaust System', 'category': 'exhaust', 'powerGain': 18, 'torqueGain': 15, 'boostGain': 0, 'timingGain': 2, 'cost': 1299, 'difficulty': 2, 'stages': [1], 'description': 'Stainless steel performance exhaust.', 'compatible': ['all'], 'requiredECU': False, 'warrantyRisk': 'Low'},
    {'id': 'downpipe', 'name': 'Mandrel Bent Downpipe (High-Flow Cat)', 'category': 'exhaust', 'powerGain': 20, 'torqueGain': 22, 'boostGain': 2, 'timingGain': 3, 'cost': 699, 'difficulty': 3, 'stages': [2], 'description': 'Eliminates restrictive catalytic converter.', 'requiredECU': True, 'requires': ['exhaust-system'], 'warrantyRisk': 'Medium', 'compatible': ['turbo']},
    {'id': 'intercooler-upgrade', 'name': 'Front Mount Intercooler Kit', 'category': 'forced-induction', 'powerGain': 25, 'torqueGain': 30, 'boostGain': 0, 'timingGain': 0, 'cost': 899, 'difficulty': 4, 'stages': [2], 'description': 'Larger core intercooler reduces intake temps.', 'compatible': ['turbo'], 'warrantyRisk': 'Medium'},
    {'id': 'ecu-remap-stage1', 'name': 'Stage 1 ECU Tune (91+ Octane)', 'category': 'tuning', 'powerGain': 45, 'torqueGain': 50, 'boostGain': 3, 'timingGain': 8, 'cost': 599, 'difficulty': 0.5, 'stages': [1], 'description': 'Optimized fuel and ignition timing.', 'requiredECU': True, 'compatible': ['all'], 'warrantyRisk': 'Medium'},
    {'id': 'ecu-remap-stage2', 'name': 'Stage 2 ECU Tune (E85 Compatible)', 'category': 'tuning', 'powerGain': 75, 'torqueGain': 85, 'boostGain': 5, 'timingGain': 12, 'cost': 799, 'difficulty': 1, 'stages': [2], 'description': 'Aggressive tune for fully bolted cars.', 'requiredECU': True, 'compatible': ['all'], 'warrantyRisk': 'High'},
    {'id': 'turbocharger', 'name': 'Complete Turbocharger Kit', 'category': 'forced-induction', 'powerGain': 150, 'torqueGain': 180, 'boostGain': 8, 'timingGain': 5, 'cost': 4999, 'difficulty': 5, 'stages': [3], 'description': 'Full bolt-on turbo system.', 'compatible': ['v6', 'v8', 'i4', 'i6'], 'warrantyRisk': 'High'},
    {'id': 'nitrous-kit', 'name': 'Nitrous Oxide System (100 HP)', 'category': 'forced-induction', 'powerGain': 100, 'torqueGain': 120, 'boostGain': 0, 'timingGain': 10, 'cost': 1500, 'difficulty': 4, 'stages': [2], 'description': 'On-demand nitrous injection.', 'compatible': ['all'], 'warrantyRisk': 'High'},
    {'id': 'sportCam', 'name': 'Stage 2 Camshaft Kit', 'category': 'engine', 'powerGain': 30, 'torqueGain': 25, 'boostGain': 0, 'timingGain': 8, 'cost': 899, 'difficulty': 4, 'stages': [2], 'description': 'Aggressive cam profile.', 'compatible': ['v8', 'v6', 'i6'], 'warrantyRisk': 'High'},
]